/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateSnapshotFromSandbox
 */
export interface CreateSnapshotFromSandbox {
    /**
     * Name for the new snapshot
     * @type {string}
     * @memberof CreateSnapshotFromSandbox
     */
    'name': string;
    /**
     * Description of the snapshot
     * @type {string}
     * @memberof CreateSnapshotFromSandbox
     */
    'description'?: string;
    /**
     * CPU cores allocated to the resulting sandbox
     * @type {number}
     * @memberof CreateSnapshotFromSandbox
     */
    'cpu'?: number;
    /**
     * GPU units allocated to the resulting sandbox
     * @type {number}
     * @memberof CreateSnapshotFromSandbox
     */
    'gpu'?: number;
    /**
     * Memory allocated to the resulting sandbox in GB
     * @type {number}
     * @memberof CreateSnapshotFromSandbox
     */
    'memory'?: number;
    /**
     * Disk space allocated to the sandbox in GB
     * @type {number}
     * @memberof CreateSnapshotFromSandbox
     */
    'disk'?: number;
}

