/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateSnapshotFromSandbox type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSnapshotFromSandbox{}

// CreateSnapshotFromSandbox struct for CreateSnapshotFromSandbox
type CreateSnapshotFromSandbox struct {
	// Name for the new snapshot
	Name string `json:"name"`
	// Description of the snapshot
	Description *string `json:"description,omitempty"`
	// CPU cores allocated to the resulting sandbox
	Cpu *int32 `json:"cpu,omitempty"`
	// GPU units allocated to the resulting sandbox
	Gpu *int32 `json:"gpu,omitempty"`
	// Memory allocated to the resulting sandbox in GB
	Memory *int32 `json:"memory,omitempty"`
	// Disk space allocated to the sandbox in GB
	Disk *int32 `json:"disk,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateSnapshotFromSandbox CreateSnapshotFromSandbox

// NewCreateSnapshotFromSandbox instantiates a new CreateSnapshotFromSandbox object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSnapshotFromSandbox(name string) *CreateSnapshotFromSandbox {
	this := CreateSnapshotFromSandbox{}
	this.Name = name
	return &this
}

// NewCreateSnapshotFromSandboxWithDefaults instantiates a new CreateSnapshotFromSandbox object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSnapshotFromSandboxWithDefaults() *CreateSnapshotFromSandbox {
	this := CreateSnapshotFromSandbox{}
	return &this
}

// GetName returns the Name field value
func (o *CreateSnapshotFromSandbox) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateSnapshotFromSandbox) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateSnapshotFromSandbox) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateSnapshotFromSandbox) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSnapshotFromSandbox) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateSnapshotFromSandbox) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateSnapshotFromSandbox) SetDescription(v string) {
	o.Description = &v
}

// GetCpu returns the Cpu field value if set, zero value otherwise.
func (o *CreateSnapshotFromSandbox) GetCpu() int32 {
	if o == nil || IsNil(o.Cpu) {
		var ret int32
		return ret
	}
	return *o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSnapshotFromSandbox) GetCpuOk() (*int32, bool) {
	if o == nil || IsNil(o.Cpu) {
		return nil, false
	}
	return o.Cpu, true
}

// HasCpu returns a boolean if a field has been set.
func (o *CreateSnapshotFromSandbox) HasCpu() bool {
	if o != nil && !IsNil(o.Cpu) {
		return true
	}

	return false
}

// SetCpu gets a reference to the given int32 and assigns it to the Cpu field.
func (o *CreateSnapshotFromSandbox) SetCpu(v int32) {
	o.Cpu = &v
}

// GetGpu returns the Gpu field value if set, zero value otherwise.
func (o *CreateSnapshotFromSandbox) GetGpu() int32 {
	if o == nil || IsNil(o.Gpu) {
		var ret int32
		return ret
	}
	return *o.Gpu
}

// GetGpuOk returns a tuple with the Gpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSnapshotFromSandbox) GetGpuOk() (*int32, bool) {
	if o == nil || IsNil(o.Gpu) {
		return nil, false
	}
	return o.Gpu, true
}

// HasGpu returns a boolean if a field has been set.
func (o *CreateSnapshotFromSandbox) HasGpu() bool {
	if o != nil && !IsNil(o.Gpu) {
		return true
	}

	return false
}

// SetGpu gets a reference to the given int32 and assigns it to the Gpu field.
func (o *CreateSnapshotFromSandbox) SetGpu(v int32) {
	o.Gpu = &v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *CreateSnapshotFromSandbox) GetMemory() int32 {
	if o == nil || IsNil(o.Memory) {
		var ret int32
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSnapshotFromSandbox) GetMemoryOk() (*int32, bool) {
	if o == nil || IsNil(o.Memory) {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *CreateSnapshotFromSandbox) HasMemory() bool {
	if o != nil && !IsNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given int32 and assigns it to the Memory field.
func (o *CreateSnapshotFromSandbox) SetMemory(v int32) {
	o.Memory = &v
}

// GetDisk returns the Disk field value if set, zero value otherwise.
func (o *CreateSnapshotFromSandbox) GetDisk() int32 {
	if o == nil || IsNil(o.Disk) {
		var ret int32
		return ret
	}
	return *o.Disk
}

// GetDiskOk returns a tuple with the Disk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSnapshotFromSandbox) GetDiskOk() (*int32, bool) {
	if o == nil || IsNil(o.Disk) {
		return nil, false
	}
	return o.Disk, true
}

// HasDisk returns a boolean if a field has been set.
func (o *CreateSnapshotFromSandbox) HasDisk() bool {
	if o != nil && !IsNil(o.Disk) {
		return true
	}

	return false
}

// SetDisk gets a reference to the given int32 and assigns it to the Disk field.
func (o *CreateSnapshotFromSandbox) SetDisk(v int32) {
	o.Disk = &v
}

func (o CreateSnapshotFromSandbox) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSnapshotFromSandbox) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Cpu) {
		toSerialize["cpu"] = o.Cpu
	}
	if !IsNil(o.Gpu) {
		toSerialize["gpu"] = o.Gpu
	}
	if !IsNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	if !IsNil(o.Disk) {
		toSerialize["disk"] = o.Disk
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateSnapshotFromSandbox) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSnapshotFromSandbox := _CreateSnapshotFromSandbox{}

	err = json.Unmarshal(data, &varCreateSnapshotFromSandbox)

	if err != nil {
		return err
	}

	*o = CreateSnapshotFromSandbox(varCreateSnapshotFromSandbox)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "cpu")
		delete(additionalProperties, "gpu")
		delete(additionalProperties, "memory")
		delete(additionalProperties, "disk")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateSnapshotFromSandbox struct {
	value *CreateSnapshotFromSandbox
	isSet bool
}

func (v NullableCreateSnapshotFromSandbox) Get() *CreateSnapshotFromSandbox {
	return v.value
}

func (v *NullableCreateSnapshotFromSandbox) Set(val *CreateSnapshotFromSandbox) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSnapshotFromSandbox) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSnapshotFromSandbox) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSnapshotFromSandbox(val *CreateSnapshotFromSandbox) *NullableCreateSnapshotFromSandbox {
	return &NullableCreateSnapshotFromSandbox{value: val, isSet: true}
}

func (v NullableCreateSnapshotFromSandbox) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSnapshotFromSandbox) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


